services:
  backend:
    build: backend/ # zbuilduje sa z Dockerfile v backend/
    ports:
      - 8000:8000 # server uvicorn bezi deafult na 8000, local:container
    depends_on: # backend pocka, kym DB bude healthy
      db:
        condition: service_healthy
    environment: # env vars su v .env subore
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/tasks
    networks:
      - taskmaster-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} # auto vytvorenie DB
    volumes:
      - postgres_db_data:/var/lib/postgresql/data # named volume, docker managed
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # auto vytvori tabulky
    networks:
      - taskmaster-network
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U {POSTGRES_USER} -d ${POSTGRES_DB}"] # overenie ci DB prijima connections
      interval: 5s # Docker spustí healthcheck každých 5 sekúnd.
      timeout: 5s # Ak pg_isready neodpovie do 5 sekúnd, healthcheck zlyhá.
      retries: 5 # Po 5 neúspešných pokusoch bude služba považovaná za nezdravú.

volumes:
  postgres_db_data:
    driver: local # data na local disk, moze byt cloud -> napr: rexray/ebs

networks: # backend a DB su v jednej sieti
  taskmaster-network:
    driver: bridge # veth for each container, DG -> docker0
