services:
  backend:
    build: backend/
    ports:
      - 8000:8000
    depends_on: 
      - db
    networks:
      - taskmaster-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=tasks
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taskmaster-network

volumes:
  postgres_db_data:
    driver: local

networks:
  taskmaster-network:
    driver: bridge
