services:
  backend:
    build: backend/
    ports:
      - 8000:8000
    depends_on: 
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/tasks
    networks:
      - taskmaster-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taskmaster-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tasks"]
      interval: 5s # Docker spustí healthcheck každých 5 sekúnd.
      timeout: 5s # Ak pg_isready neodpovie do 5 sekúnd, healthcheck zlyhá.
      retries: 5 # Po 5 neúspešných pokusoch bude služba považovaná za nezdravú.

volumes:
  postgres_db_data:
    driver: local

networks:
  taskmaster-network:
    driver: bridge
